### ISSUE TITLE
Check if the current application is JupyterLite

### ISSUE THREAD

**Issue by brichet** [jupyterlite/litegitpuller#5]
The plugin should run only on *Jupyterlite* , to avoid conflicts with *nbgitpuller* if installed alongside this extension on *Jupyterlab*.

### Problem

Check if the current application is *Jupyterlite* and not Jupyterlab.

### Additional context

See comment https://github.com/jupyterlite/litegitpuller/pull/4#discussion_r1313338563

**Comment by jtpio** [comment]
Or as an alternative to checking for JupyterLab or JupyterLite, maybe checking whether the `nbgitpuller` extension is available?

**Comment by brichet** [comment]
Right.
According to you, is there a way to test a server extension from the frontend ? 
The only way I can think of is to use the Rest API ?

**Comment by jtpio** [comment]
Maybe making a request to one of the `nbgitpuller` endpoints would work?

**Comment by bollwyvl** [comment]
Yep, we've tried really hard to to make it _hard_ to tell if an extension is running in lite to avoid making things that _would_ work in Lab _only_ work in lite.

Perhaps lite core needs a marker token in the "client" side of the app, similar to `optional: [ILabShell]` (useful for distinguishing between lab and notebook). As the switch to `@jupyterlite/* 0.2.0` is imminent, perhaps this could be something very small, e.g. an `ILiteInfo` extension, which consolidated some common access patterns _and_ contained the cooked-in version (e.g from `package.json`, not `PageConfig` strings, which can be changed, by design).

**Comment by brichet** [comment]
> Yep, we've tried really hard to to make it _hard_ to tell if an extension is running in lite to avoid making things that _would_ work in Lab _only_ work in lite.

This is exactly what I'm trying to do :smile: 

In that specific case @jtpio is right, it should not run only if nbgitpuller is installed, otherwise it can run in lab.

**Comment by juntyr** [comment]
I just came across this issue myself - I am hosting a JupyterLite application with litegitpuller installed, but it does not work because my app is renamed. Would it be possible to perform the check in a more robust way or disable it?

**Comment by brichet** [comment]
Thanks @juntyr for reviving this issue.
I opened https://github.com/jupyterlite/litegitpuller/pull/20 to fix it.
